# Generated by Django 3.2 on 2021-04-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_contact_number_costumer_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='is_online',
            new_name='is_active',
        ),
    ]
