# Generated by Django 3.2 on 2021-04-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_online_costumer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
