# Generated by Django 3.2 on 2021-06-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_costumer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='contact',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
